### ISSUE TITLE
After Upgrade: Unable to find not active module to execute: -X> modules/Build/Build.groovy

### ISSUE THREAD

**Issue by dolphinscorp** [griddynamics/mpl#108]
hi
We have upgrade jenkins from 2.385 to 2.444 Now getting this error. Before upgrade it was working fine 

```
Also: org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: b1f15905-6959-48d5-a6ae-5257eb3e5928 hudson.remoting.ProxyException: com.griddynamics.devops.mpl.MPLModuleException: Unable to find not active module to execute: -X> modules/Build/Build.groovy at [MPLModule.call](http://mplmodule.call/)(MPLModule.groovy:79) at [MPLModule.call](http://mplmodule.call/)(MPLModule.groovy) at [MPLPipeline.call](http://mplpipeline.call/)(MPLPipeline.groovy:65) at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.delegateAndExecute(ModelInterpreter.groovy:138) at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.executeSingleStage(ModelInterpreter.groovy:673) at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.catchRequiredContextForNode(ModelInterpreter.groovy:402) at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.catchRequiredContextForNode(ModelInterpreter.groovy:400) at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.executeSingleStage(ModelInterpreter.groovy:672) at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.evaluateStage(ModelInterpreter.groovy:294) at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.toolsBlock(ModelInterpreter.groovy:551) at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.toolsBlock(ModelInterpreter.groovy:550) at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.evaluateStage(ModelInterpreter.groovy:282) at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.withEnvBlock(ModelInterpreter.groovy:450) at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.withEnvBlock(ModelInterpreter.groovy:449) at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.evaluateStage(ModelInterpreter.groovy:281) at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.withCredentialsBlock(ModelInterpreter.groovy:488) at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.withCredentialsBlock(ModelInterpreter.groovy:487) at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.evaluateStage(ModelInterpreter.groovy:280) at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.inDeclarativeAgent(ModelInterpreter.groovy:593) at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.inDeclarativeAgent(ModelInterpreter.groovy:592) at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.evaluateStage(ModelInterpreter.groovy:278) at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.stageInput(ModelInterpreter.groovy:362) at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.stageInput(ModelInterpreter.groovy:361) at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.evaluateStage(ModelInterpreter.groovy:267) at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.inWrappers(ModelInterpreter.groovy:625) at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.inWrappers(ModelInterpreter.groovy:624) at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.evaluateStage(ModelInterpreter.groovy:265) at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.withEnvBlock(ModelInterpreter.groovy:450) at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.withEnvBlock(ModelInterpreter.groovy:449) at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.evaluateStage(ModelInterpreter.groovy:260) at \\cps.transform\(Native Method) at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance([NativeConstructorAccessorImpl.java:62](http://nativeconstructoraccessorimpl.java:62/)) at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance([DelegatingConstructorAccessorImpl.java:45](http://delegatingconstructoraccessorimpl.java:45/)) at java.base/java.lang.reflect.Constructor.newInstance([Constructor.java:490](http://constructor.java:490/)) at org.codehaus.groovy.reflection.CachedConstructor.invoke([CachedConstructor.java:83](http://cachedconstructor.java:83/)) at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke([CachedConstructor.java:77](http://cachedconstructor.java:77/)) at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor([ConstructorSite.java:84](http://constructorsite.java:84/)) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor([CallSiteArray.java:59](http://callsitearray.java:59/)) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor([AbstractCallSite.java:238](http://abstractcallsite.java:238/)) at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.constructorCall([DefaultInvoker.java:25](http://defaultinvoker.java:25/)) at org.jenkinsci.plugins.workflow.cps.LoggingInvoker.constructorCall([LoggingInvoker.java:110](http://logginginvoker.java:110/)) at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg([FunctionCallBlock.java:100](http://functioncallblock.java:100/)) at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg([FunctionCallBlock.java:85](http://functioncallblock.java:85/)) at jdk.internal.reflect.GeneratedMethodAccessor211.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke([DelegatingMethodAccessorImpl.java:43](http://delegatingmethodaccessorimpl.java:43/)) at java.base/java.lang.reflect.Method.invoke([Method.java:566](http://method.java:566/)) at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive([ContinuationPtr.java:72](http://continuationptr.java:72/)) at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg([FunctionCallBlock.java:110](http://functioncallblock.java:110/)) at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg([FunctionCallBlock.java:85](http://functioncallblock.java:85/)) at jdk.internal.reflect.GeneratedMethodAccessor211.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke([DelegatingMethodAccessorImpl.java:43](http://delegatingmethodaccessorimpl.java:43/)) at java.base/java.lang.reflect.Method.invoke([Method.java:566](http://method.java:566/)) at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive([ContinuationPtr.java:72](http://continuationptr.java:72/)) at com.cloudbees.groovy.cps.impl.CastBlock$ContinuationImpl.cast([CastBlock.java:47](http://castblock.java:47/)) at jdk.internal.reflect.GeneratedMethodAccessor245.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke([DelegatingMethodAccessorImpl.java:43](http://delegatingmethodaccessorimpl.java:43/)) at java.base/java.lang.reflect.Method.invoke([Method.java:566](http://method.java:566/)) at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive([ContinuationPtr.java:72](http://continuationptr.java:72/)) at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.dispatch([CollectionLiteralBlock.java:55](http://collectionliteralblock.java:55/)) at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.item([CollectionLiteralBlock.java:45](http://collectionliteralblock.java:45/)) at jdk.internal.reflect.GeneratedMethodAccessor244.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke([DelegatingMethodAccessorImpl.java:43](http://delegatingmethodaccessorimpl.java:43/)) at java.base/java.lang.reflect.Method.invoke([Method.java:566](http://method.java:566/)) at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive([ContinuationPtr.java:72](http://continuationptr.java:72/)) at com.cloudbees.groovy.cps.impl.ConstantBlock.eval([ConstantBlock.java:21](http://constantblock.java:21/)) at [com.cloudbees.groovy.cps.Next](http://com.cloudbees.groovy.cps.next/).step([Next.java:83](http://next.java:83/)) at [com.cloudbees.groovy.cps.Continuable.run](http://com.cloudbees.groovy.cps.continuable.run/)0([Continuable.java:147](http://continuable.java:147/)) at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001([SandboxContinuable.java:17](http://sandboxcontinuable.java:17/)) at [org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run](http://org.jenkinsci.plugins.workflow.cps.sandboxcontinuable.run/)0([SandboxContinuable.java:49](http://sandboxcontinuable.java:49/)) at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk([CpsThread.java:180](http://cpsthread.java:180/)) at [org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run](http://org.jenkinsci.plugins.workflow.cps.cpsthreadgroup.run/)([CpsThreadGroup.java:423](http://cpsthreadgroup.java:423/)) at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$[2.call](http://2.call/)([CpsThreadGroup.java:331](http://cpsthreadgroup.java:331/)) at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$[2.call](http://2.call/)([CpsThreadGroup.java:295](http://cpsthreadgroup.java:295/)) at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService.lambda$wrap$4([CpsVmExecutorService.java:136](http://cpsvmexecutorservice.java:136/)) at java.base/[java.util.concurrent.FutureTask.run](http://java.util.concurrent.futuretask.run/)([FutureTask.java:264](http://futuretask.java:264/)) at hudson.remoting.SingleLaneExecutorService$[1.run](http://1.run/)([SingleLaneExecutorService.java:139](http://singlelaneexecutorservice.java:139/)) at jenkins.util.ContextResettingExecutorService$[1.run](http://1.run/)([ContextResettingExecutorService.java:28](http://contextresettingexecutorservice.java:28/)) at [jenkins.security](http://jenkins.security/).ImpersonatingExecutorService$[1.run](http://1.run/)([ImpersonatingExecutorService.java:68](http://impersonatingexecutorservice.java:68/)) at jenkins.util.ErrorLoggingExecutorService.lambda$wrap$0([ErrorLoggingExecutorService.java:51](http://errorloggingexecutorservice.java:51/)) at java.base/java.util.concurrent.Executors$[RunnableAdapter.call](http://runnableadapter.call/)([Executors.java:515](http://executors.java:515/)) at java.base/[java.util.concurrent.FutureTask.run](http://java.util.concurrent.futuretask.run/)([FutureTask.java:264](http://futuretask.java:264/)) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker([ThreadPoolExecutor.java:1128](http://threadpoolexecutor.java:1128/)) at java.base/java.util.concurrent.ThreadPoolExecutor$[Worker.run](http://worker.run/)([ThreadPoolExecutor.java:628](http://threadpoolexecutor.java:628/)) at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$[1.call](http://1.call/)([CpsVmExecutorService.java:53](http://cpsvmexecutorservice.java:53/)) at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$[1.call](http://1.call/)([CpsVmExecutorService.java:50](http://cpsvmexecutorservice.java:50/)) at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use([GroovyCategorySupport.java:136](http://groovycategorysupport.java:136/)) at org.codehaus.groovy.runtime.GroovyCategorySupport.use([GroovyCategorySupport.java:275](http://groovycategorysupport.java:275/)) at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService.lambda$categoryThreadFactory$0([CpsVmExecutorService.java:50](http://cpsvmexecutorservice.java:50/)) at java.base/[java.lang.Thread.run](http://java.lang.thread.run/)([Thread.java:829](http://thread.java:829/)) [Bitbucket] Notifying commit build result [Bitbucket] Build result notified Finished: FAILURE
```

**Comment by dolphinscorp** [comment]
@sparshev @emelianrus @sdkrach @kvmenshikov @TheTechOddBug 

please help

**Comment by sparshev** [comment]
Oh my, weird thing. Did you tried to move back to 2.385 - that fixes the issue?

**Comment by sparshev** [comment]
Will close as stale issue, please feel free to reopen if it was closed too early.
