### ISSUE TITLE
Pipeline fails after latest changes

### ISSUE THREAD

**Issue by marcelaraujo** [griddynamics/mpl#62]
```
hudson.remoting.ProxyException: com.griddynamics.devops.mpl.MPLModuleException: Found error during execution of the module 'library:jenkins-mpl-library/resources/com/griddynamics/devops/mpl/modules/Build/Build.groovy#null':
com.griddynamics.devops.mpl.MPLModuleException: Found error during execution of the module 'library:jenkins-mpl-library/resources/com/griddynamics/devops/mpl/modules/Build/MavenBuild.groovy#null':
hudson.AbortException: No tool named Maven 3 found
	at org.jenkinsci.plugins.workflow.steps.ToolStep$Execution.run(ToolStep.java:162)
	at org.jenkinsci.plugins.workflow.steps.ToolStep$Execution.run(ToolStep.java:133)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

My Jenkinsfile

```
def call(body) {
    MPLModulesPath('org/jenkins/pipeline/modules')
    ...
}
```

**Comment by sparshev** [comment]
Hi @marcelaraujo ,

Did you read the exception? Also please check the first example here: https://github.com/griddynamics/mpl/wiki/MPL-Build-example

**Comment by marcelaraujo** [comment]
Yeah, I did. This issue happens because in your repository has a default path module.

Please, ignore this issue.
